#!/usr/bin/env bash
# Composite status line — runs several segments and joins whatever they print.
#
#   TO ADD A SEGMENT: add a line to the list below. That is the whole procedure.
#
# A segment is any shell command that reads the status-line JSON on stdin and
# prints one short line (or nothing). Every segment gets the same input, they run
# in parallel, and one that prints nothing contributes nothing — no stray
# separators. A segment that hangs, crashes, or does not exist is dropped.
#
# Generated by teamlead's install-statusline.sh. Safe to edit by hand; the
# installer will not overwrite it without asking.

SEGMENTS=(
__SEGMENTS__
)

SEP=" "          # what goes between segments
TIMEOUT=2        # seconds any one segment may take before it is dropped

# --- nothing below here needs editing to add a segment ----------------------
set -uo pipefail
in=$(cat 2>/dev/null)

# Run every segment at once. Serially the prompt waits for the SUM of them; one
# slow git call times however many segments you have adds up fast. In parallel the
# cost is just the slowest.
tmp=$(mktemp -d) || exit 0
trap 'rm -rf "$tmp"' EXIT

i=0
for cmd in "${SEGMENTS[@]}"; do
  i=$((i + 1))
  # "$cmd" must resolve to exactly one command here — a de-pinned plugin-cache
  # segment carries its own quoted `compgen -G ... | sort -V | tail -1` glob
  # resolution (see install-statusline.sh's depin()), never a bare unquoted `*`
  # that would explode into multiple words for `bash -c` on a two-version cache.
  printf '%s' "$in" | timeout "$TIMEOUT" bash -c "$cmd" >"$tmp/$i" 2>/dev/null &
done
wait

out=()
for n in $(seq 1 $i); do                       # reassemble in listed order
  [ -s "$tmp/$n" ] || continue
  seg=$(cat "$tmp/$n"); seg=${seg%$'\n'}
  [ -n "$seg" ] && out+=("$seg")
done

(IFS="$SEP"; printf '%s' "${out[*]-}")
